
@startuml casosDeUso
left to right direction
skinparam packageStyle rectangle

actor Aluno
actor Professor
actor Coordenador
actor "SGBD" as SGBD

rectangle "Sistema de Jogo Educacional" {

  usecase "Realizar Login" as UC1
  usecase "Jogar Partida" as UC2
  usecase "Usar Ajuda" as UC2_1
  usecase "Responder Pergunta" as UC2_2
  usecase "Visualizar Estatísticas" as UC3

  usecase "Cadastrar Pergunta" as UC4
  usecase "Editar Pergunta" as UC7
  usecase "Cadastrar Aluno" as UC5
  usecase "Cadastrar Professor" as UC6
  usecase "Testar como Aluno" as UC8

  usecase "Persistir Dados" as DB1
  usecase "Consultar Dados" as DB2

  Aluno --> UC1
  Aluno --> UC2
  UC2 --> UC2_1 : <<extend>>
  UC2 --> UC2_2 : <<include>>
  Aluno --> UC3

  Professor --> UC1
  Professor --> UC4
  Professor --> UC5
  Professor --> UC7
  Professor --> UC3
  Professor --> UC8

  Coordenador --> UC1
  Coordenador --> UC6

  UC4 --> DB1 : <<include>>
  UC5 --> DB1 : <<include>>
  UC6 --> DB1 : <<include>>
  UC7 --> DB1 : <<include>>
  UC3 --> DB2 : <<include>>
  UC2 --> DB2 : <<include>>
  UC1 --> DB2 : <<include>>
}

SGBD <-- DB1
SGBD <-- DB2
@enduml
