
@startuml estadoPergunta
[*] --> Rascunho

Rascunho --> Validada : validar()
Validada --> Publicada : salvarNoBanco()
Publicada --> UsadaEmJogo : sorteadaParaJogo()
UsadaEmJogo --> UsadaEmJogo : novaSorteio()
UsadaEmJogo --> Editada : editar()

Editada --> Validada : revalidar()
Editada --> Publicada : salvarNovamente()

Publicada --> Inativa : desativar()
Inativa --> [*]
@enduml
