
@startuml objetosJogo
object "Aluno\nJoão da Silva" as aluno
object "Professor\nMaria Oliveira" as professor
object "Pergunta\nQual é a capital da França?" as pergunta
object "Resposta\nParis (correta)" as resposta1
object "Resposta\nRoma (incorreta)" as resposta2

aluno --> resposta1 : respondeu
aluno --> professor : vinculado a
professor --> pergunta : cadastrou
pergunta --> resposta1
pergunta --> resposta2
@enduml
