
@startuml sequenciaCadastrarPergunta
actor Professor

participant TelaGerenciamentoProfessor
participant Pergunta
participant Resposta
participant DAO
database SGBD

Professor -> TelaGerenciamentoProfessor : preencherCamposPergunta()
TelaGerenciamentoProfessor -> Pergunta : new Pergunta(...)
TelaGerenciamentoProfessor -> Resposta : new Resposta(...) x4

TelaGerenciamentoProfessor -> DAO : salvarPergunta(pergunta, respostas)
DAO -> SGBD : INSERT INTO perguntas (...)
SGBD --> DAO : id_pergunta
DAO -> SGBD : INSERT INTO respostas (...) [4x]
SGBD --> DAO : sucesso

DAO --> TelaGerenciamentoProfessor : confirmação
TelaGerenciamentoProfessor -> Professor : mostrarMensagem("Pergunta cadastrada com sucesso")
@enduml
