
@startuml CadastrarProfessor
|Coordenador|
start
:Preencher dados do novo professor;
:Clicar em "Cadastrar";

|View|
:Enviar dados;

|Controller|
:Instanciar Professor;
:Validar dados;

|DAO/SGBD|
:INSERT na tabela professor;

|Controller|
:Retornar status;

|View|
:Exibir resultado;

|Coordenador|
stop
@enduml
