
@startuml EstatisticasDiagram
|Professor|
start
:Clicar em "Estatísticas";

|View|
:Solicitar estatísticas ao controlador;

|Controller|
:Selecionar tipo de estatística;

|DAO/SGBD|
:Executar SELECTs agregados;

|Controller|
:Organizar dados;

|View|
:Exibir gráficos ou tabelas;
|Professor|
stop
@enduml
